In [ ]:
import os
import json
import pandas as pd

In [ ]:
!pip install -r requirements.txt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!unzip /content/drive/MyDrive/data.zip -d /content/data

Archive:  /content/drive/MyDrive/data.zip
replace /content/data/data/open-data/data/competitions.json? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
import os

TM_PATH = '/content/data/data/transfermarkt-datasets'

files = os.listdir(TM_PATH)

for f in files:
    print(f)

clubs.csv.gz
games.csv.gz
game_lineups.csv.gz
club_games.csv.gz
player_valuations.csv.gz
competitions.csv.gz
appearances.csv.gz
players.csv.gz
transfers.csv.gz
game_events.csv.gz

In [ ]:
def preview_table(file, n=5):
    df = pd.read_csv(f"{TM_PATH}/{file}", nrows=n)
    print(f"\n📄 {file}")
    print("Shape preview:", df.shape)
    print("Columns:", df.columns.tolist())
    display(df)

for file in files:
    preview_table(file)

📄 clubs.csv.gz
Shape preview: (5, 17)
Columns: ['club_id', 'club_code', 'name', 'domestic_competition_id', 'total_market_value', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'national_team_players', 'stadium_name', 'stadium_seats', 'net_transfer_record', 'coach_name', 'last_season', 'filename', 'url']

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris Football Club,FR1,NaN,31,28.5,17,54.8,9,Stade Jean Bouin,19904,€-72.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,10,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
3,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.1,23,85.2,10,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...
4,1010,fc-watford,Watford FC,GB1,NaN,30,26.3,24,80.0,12,Vicarage Road,21577,+€42.02m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/fc-watford/sta...

📄 games.csv.gz
Shape preview: (5, 23)
Columns: ['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id', 'away_club_id', 'home_club_goals', 'away_club_goals', 'home_club_position', 'away_club_position', 'home_club_manager_name', 'away_club_manager_name', 'stadium', 'attendance', 'referee', 'url', 'home_club_formation', 'away_club_formation', 'home_club_name', 'away_club_name', 'aggregate', 'competition_type']

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2211607,NLSC,2012,Final,2012-08-05,383,610,4,2,NaN,...,Johan Cruijff ArenA,50000,Björn Kuipers,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Eindhovense Voetbalvereniging Philips Sport Ve...,AFC Ajax Amsterdam,4:2,other
1,2218677,SCI,2012,Final,2012-08-11,506,6195,4,2,NaN,...,National Stadium (Bird's Nest),60000,Paolo Silvio Mazzoleni,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Juventus Football Club,Società Sportiva Calcio Napoli,4:2,other
2,2219794,BESC,2012,Final,2012-07-22,58,498,3,2,NaN,...,Constant Vanden Stock Stadion,14485,Laurent Colemonts,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Royal Sporting Club Anderlecht,KSC Lokeren (- 2020),3:2,other
3,2219795,USC,2012,Final,2012-08-31,631,13,1,4,NaN,...,Stade Louis-II,14312,Damir Skomina,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Chelsea Football Club,Club Atlético de Madrid S.A.D.,1:4,international_cup
4,2221641,DFB,2012,First Round,2012-08-19,1203,42,1,6,NaN,...,Stadion an der Kreuzeiche,3168,Benjamin Cortus,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,FC Nöttingen,Hannover 96,1:6,domestic_cup

📄 game_lineups.csv.gz
Shape preview: (5, 10)
Columns: ['game_lineups_id', 'date', 'game_id', 'player_id', 'club_id', 'player_name', 'type', 'position', 'number', 'team_captain']

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

📄 club_games.csv.gz
Shape preview: (5, 11)
Columns: ['game_id', 'club_id', 'own_goals', 'own_position', 'own_manager_name', 'opponent_id', 'opponent_goals', 'opponent_position', 'opponent_manager_name', 'hosting', 'is_win']

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,2211607,383,4,NaN,Dick Advocaat,610,2,NaN,Frank de Boer,Home,1
1,2211607,610,2,NaN,Frank de Boer,383,4,NaN,Dick Advocaat,Away,0
2,2218677,506,4,NaN,Massimo Carrera,6195,2,NaN,Walter Mazzarri,Home,1
3,2218677,6195,2,NaN,Walter Mazzarri,506,4,NaN,Massimo Carrera,Away,0
4,2219794,58,3,NaN,John van den Brom,498,2,NaN,Peter Maes,Home,1

📄 player_valuations.csv.gz
Shape preview: (5, 6)
Columns: ['player_id', 'date', 'market_value_in_eur', 'current_club_name', 'current_club_id', 'player_club_domestic_competition_id']

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

📄 competitions.csv.gz
Shape preview: (5, 11)
Columns: ['competition_id', 'competition_code', 'name', 'sub_type', 'type', 'country_id', 'country_name', 'domestic_league_code', 'confederation', 'url', 'is_major_national_league']

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url,is_major_national_league
0,BE1,jupiler-pro-league,jupiler-pro-league,first_tier,domestic_league,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/jupiler-pro-le...,False
1,BESC,belgian-supercup,belgian-supercup,domestic_super_cup,other,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/belgian-superc...,False
2,CDR,copa-del-rey,copa-del-rey,domestic_cup,domestic_cup,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/copa-del-rey/s...,False
3,CGB,efl-cup,efl-cup,league_cup,other,189,England,GB1,europa,https://www.transfermarkt.co.uk/efl-cup/starts...,False
4,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,False

📄 appearances.csv.gz
Shape preview: (5, 13)
Columns: ['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'date', 'player_name', 'competition_id', 'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

📄 players.csv.gz
Shape preview: (5, 23)
Columns: ['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000,30000000
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000,8000000
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000,34500000
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000,24500000
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000,3000000

📄 transfers.csv.gz
Shape preview: (5, 10)
Columns: ['player_id', 'transfer_date', 'transfer_season', 'from_club_id', 'to_club_id', 'from_club_name', 'to_club_name', 'transfer_fee', 'market_value_in_eur', 'player_name']

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,739277,2027-05-30,26/27,42055,589,Genclik Gücü,Antalyaspor,0.0,NaN,Yannick Nkurunziza
2,1043003,2027-01-27,26/27,114,405,Besiktas,Aston Villa,0.0,5000000.0,Yasin Özcan
3,282727,2026-12-31,25/26,49283,605,FC Juárez,Aris Saloniki,0.0,6000000.0,Monchu
4,371996,2026-12-31,26/27,6600,2410,Internacional,CSKA Moscow,0.0,3000000.0,Alerrandro

📄 game_events.csv.gz
Shape preview: (5, 11)
Columns: ['game_event_id', 'date', 'game_id', 'minute', 'type', 'club_id', 'club_name', 'player_id', 'description', 'player_in_id', 'player_assist_id']

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,Ajax Amsterdam,4425,"1. Yellow card , Mass confrontation",NaN,NaN
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,PSV Eindhoven,33210,"1. Yellow card , Mass confrontation",NaN,NaN
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,PSV Eindhoven,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,PSV Eindhoven,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,PSV Eindhoven,36500,", Not reported",49499.0,NaN

In [ ]:
import os

TM2_PATH = '/content/data/data/transfermarkt'

files2 = os.listdir(TM2_PATH)

for f in files2:
    print(f)

team_details
transfer_history
player_injuries
player_performances
player_market_value
player_latest_market_value
team_competitions_seasons
player_national_performances
player_teammates_played_with
team_children
player_profiles

In [ ]:
def preview_table_advanced(file, path, n=5):
    full_path = f"{path}/{file}"

    # Skip folders
    if os.path.isdir(full_path):
        return

    df = pd.read_csv(full_path, nrows=100)

    print(f"\n📄 {file}")
    print("Columns:", df.columns.tolist())
    print("Missing values:\n", df.isnull().sum())
    print("Data types:\n", df.dtypes)

    display(df.head(n))


for file in files2:
    preview_table_advanced(file, TM2_PATH)

In [ ]:
def preview_transfermarkt(path, n=5):

    for folder in os.listdir(path):
        folder_path = os.path.join(path, folder)

        # Only explore folders
        if os.path.isdir(folder_path):
            print(f"\n📂 Folder: {folder}")

            files = os.listdir(folder_path)

            for file in files[:2]:  # limit to 2 files per folder
                file_path = os.path.join(folder_path, file)

                try:
                    df = pd.read_csv(file_path, nrows=100)

                    print(f"\n📄 {file}")
                    print("Columns:", df.columns.tolist())
                    print("Missing values:\n", df.isnull().sum())

                    display(df.head(n))

                except Exception as e:
                    print(f"❌ Could not read {file}: {e}")

In [ ]:
import os
import pandas as pd

TM2_PATH = '/content/data/data/transfermarkt'

def preview_transfermarkt(path, n=5, max_files_per_folder=2):

    for folder in os.listdir(path):
        folder_path = os.path.join(path, folder)

        # Only process folders
        if os.path.isdir(folder_path):
            print(f"\n📂 Folder: {folder}")

            files = os.listdir(folder_path)

            for file in files[:max_files_per_folder]:  # limit files per folder
                file_path = os.path.join(folder_path, file)

                try:
                    df = pd.read_csv(file_path, nrows=100)

                    print(f"\n📄 File: {file}")
                    print("Columns:", df.columns.tolist())
                    print("Missing values:\n", df.isnull().sum())
                    print("Data types:\n", df.dtypes)

                    display(df.head(n))

                except Exception as e:
                    print(f"❌ Could not read {file}: {e}")


# ▶️ Run
preview_transfermarkt(TM2_PATH)

📂 Folder: team_details

📄 File: team_details.csv
Columns: ['club_id', 'club_slug', 'club_name', 'logo_url', 'country_name', 'season_id', 'competition_id', 'competition_slug', 'competition_name', 'club_division', 'source_url', '_last_modified_at']
Missing values:
 club_id               0
club_slug             0
club_name             0
logo_url              0
country_name          0
season_id             0
competition_id       14
competition_slug     14
competition_name     14
club_division        14
source_url            0
_last_modified_at     0
dtype: int64
Data types:
 club_id               int64
club_slug            object
club_name            object
logo_url             object
country_name         object
season_id             int64
competition_id       object
competition_slug     object
competition_name     object
club_division        object
source_url           object
_last_modified_at    object
dtype: object

,club_id,club_slug,club_name,logo_url,country_name,season_id,competition_id,competition_slug,competition_name,club_division,source_url,_last_modified_at
0,100335,cd-mafra-sub-23,CD Mafra U23 (100335),https://tmssl.akamaized.net//images/wappen/hea...,Portugal,2023,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/cd-mafra-sub-23/...,2025-09-11 20:20:19
1,100431,napoli-under-18,Napoli Under 18 (100431),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2021,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/napoli-under-18/...,2025-09-13 09:55:03
2,101416,venezia-under-18,Venezia Under 18 (101416),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2022,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/venezia-under-18...,2025-09-13 09:37:05
3,100461,lecce-under-18,Lecce Under 18 (100461),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2015,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/lecce-under-18/s...,2025-09-13 09:52:59
4,10010,esporte-clube-bahia,Esporte Clube Bahia (10010),https://tmssl.akamaized.net//images/wappen/hea...,Brazil,2006,BRA1,campeonato-brasileiro-serie-a,Campeonato Brasileiro Série A,Campeonato Brasileiro Série A,https://www.transfermarkt.com/esporte-clube-ba...,2025-09-13 11:59:31

📂 Folder: transfer_history

📄 File: transfer_history.csv
Columns: ['version https://git-lfs.github.com/spec/v1']
Missing values:
 version https://git-lfs.github.com/spec/v1    0
dtype: int64
Data types:
 version https://git-lfs.github.com/spec/v1    object
dtype: object

          version https://git-lfs.github.com/spec/v1
0  oid sha256:5c602e631654e2f25a646d88a47bf7070e3...
1                                      size 81069349

📂 Folder: player_injuries

📄 File: player_injuries.csv
Columns: ['player_id', 'season_name', 'injury_reason', 'from_date', 'end_date', 'days_missed', 'games_missed']
Missing values:
 player_id        0
season_name      0
injury_reason    0
from_date        0
end_date         4
days_missed      0
games_missed     0
dtype: int64
Data types:
 player_id          int64
season_name       object
injury_reason     object
from_date         object
end_date          object
days_missed      float64
games_missed       int64
dtype: object

,player_id,season_name,injury_reason,from_date,end_date,days_missed,games_missed
0,10,15/16,Hand injury,2016-04-19,2016-04-29,11.0,2
1,10,15/16,Thigh problems,2015-12-18,2015-12-31,14.0,1
2,10,15/16,Capsular injury,2015-11-11,2015-11-21,11.0,0
3,10,15/16,Rest,2015-11-04,2015-11-06,3.0,1
4,10,15/16,Hamstring injury,2015-08-20,2015-10-08,50.0,10

📂 Folder: player_performances

📄 File: player_performances.csv
Columns: ['version https://git-lfs.github.com/spec/v1']
Missing values:
 version https://git-lfs.github.com/spec/v1    0
dtype: int64
Data types:
 version https://git-lfs.github.com/spec/v1    object
dtype: object

          version https://git-lfs.github.com/spec/v1
0  oid sha256:21eda6556654478fe986de8972d3b94aea6...
1                                     size 157647289

📂 Folder: player_market_value

📄 File: player_market_value.csv
Columns: ['player_id', 'date_unix', 'value']
Missing values:
 player_id    0
date_unix    0
value        0
dtype: int64
Data types:
 player_id      int64
date_unix     object
value        float64
dtype: object

   player_id   date_unix       value
0    1000135  2023-12-19    100000.0
1    1000135  2024-06-23    100000.0
2         10  2005-01-06   9000000.0
3         10  2008-06-03  20000000.0
4         10  2009-08-29  12000000.0

📂 Folder: player_latest_market_value

📄 File: player_latest_market_value.csv
Columns: ['player_id', 'date_unix', 'value']
Missing values:
 player_id    0
date_unix    0
value        0
dtype: int64
Data types:
 player_id      int64
date_unix     object
value        float64
dtype: object

   player_id   date_unix  value
0          1  2009-04-22    0.0
1          6  2010-08-01    0.0
2          8  2010-01-01    0.0
3         10  2016-06-30    0.0
4         11  2009-03-18    0.0

📂 Folder: team_competitions_seasons

📄 File: team_competitions_seasons.csv
Columns: ['club_division', 'club_id', 'competition_id', 'competition_name', 'season_draws', 'season_goal_difference', 'season_goals_against', 'season_goals_for', 'season_id', 'season_is_two_point_system', 'season_league_competition_id', 'season_league_league_name', 'season_league_league_slug', 'season_league_level_level_name', 'season_league_level_level_number', 'season_league_season_id', 'season_losses', 'season_manager', 'season_manager_manager_id', 'season_manager_manager_name', 'season_manager_manager_slug', 'season_points', 'season_points_against', 'season_points_for', 'season_rank', 'season_season', 'season_total_matches', 'season_wins', 'team_name']
Missing values:
 club_division                         0
club_id                               0
competition_id                        0
competition_name                      0
season_draws                          0
season_goal_difference                0
season_goals_against                  0
season_goals_for                      0
season_id                             0
season_is_two_point_system            0
season_league_competition_id          0
season_league_league_name             0
season_league_league_slug             0
season_league_level_level_name        0
season_league_level_level_number      0
season_league_season_id               0
season_losses                         0
season_manager                      100
season_manager_manager_id             6
season_manager_manager_name           6
season_manager_manager_slug           6
season_points                        34
season_points_against                66
season_points_for                    66
season_rank                           0
season_season                         0
season_total_matches                  0
season_wins                           0
team_name                             0
dtype: int64
Data types:
 club_division                        object
club_id                               int64
competition_id                       object
competition_name                     object
season_draws                          int64
season_goal_difference                int64
season_goals_against                  int64
season_goals_for                      int64
season_id                             int64
season_is_two_point_system             bool
season_league_competition_id         object
season_league_league_name            object
season_league_league_slug            object
season_league_level_level_name       object
season_league_level_level_number      int64
season_league_season_id               int64
season_losses                         int64
season_manager                      float64
season_manager_manager_id           float64
season_manager_manager_name          object
season_manager_manager_slug          object
season_points                       float64
season_points_against               float64
season_points_for                   float64
season_rank                           int64
season_season                        object
season_total_matches                  int64
season_wins                           int64
team_name                            object
dtype: object

,club_division,club_id,competition_id,competition_name,season_draws,season_goal_difference,season_goals_against,season_goals_for,season_id,season_is_two_point_system,...,season_manager_manager_name,season_manager_manager_slug,season_points,season_points_against,season_points_for,season_rank,season_season,season_total_matches,season_wins,team_name
0,Third Tier,1,L3,3. Liga,4,5,16,21,2025,False,...,Alois Schwartz,alois-schwartz,19.0,NaN,NaN,3,25/26,11,5,1.FC Saarbrücken
1,Third Tier,1,L3,3. Liga,11,12,47,59,2024,False,...,Alois Schwartz,alois-schwartz,65.0,NaN,NaN,3,24/25,38,18,1.FC Saarbrücken
2,Third Tier,1,L3,3. Liga,15,17,43,60,2023,False,...,Rüdiger Ziehl,rudiger-ziehl,60.0,NaN,NaN,5,23/24,38,15,1.FC Saarbrücken
3,Third Tier,1,L3,3. Liga,9,25,39,64,2022,False,...,Rüdiger Ziehl,rudiger-ziehl,69.0,NaN,NaN,5,22/23,38,20,1.FC Saarbrücken
4,Third Tier,1,L3,3. Liga,11,6,44,50,2021,False,...,Uwe Koschinat,uwe-koschinat,53.0,NaN,NaN,7,21/22,36,14,1.FC Saarbrücken

📂 Folder: player_national_performances

📄 File: player_national_performances.csv
Columns: ['player_id', 'team_id', 'matches', 'goals', 'shirt_number', 'debut', 'coach_id', 'debut_game_id', 'career_state']
Missing values:
 player_id          0
team_id            0
matches            0
goals              0
shirt_number       0
debut            100
coach_id          33
debut_game_id     26
career_state       0
dtype: int64
Data types:
 player_id          int64
team_id            int64
matches            int64
goals              int64
shirt_number       int64
debut            float64
coach_id         float64
debut_game_id    float64
career_state      object
dtype: object

,player_id,team_id,matches,goals,shirt_number,debut,coach_id,debut_game_id,career_state
0,1,9067,1,0,0,NaN,NaN,2633677.0,FORMER_NATIONAL_PLAYER
1,1,17368,8,3,0,NaN,NaN,NaN,FORMER_NATIONAL_PLAYER
2,1,17662,14,8,18,NaN,4275.0,2359032.0,FORMER_NATIONAL_PLAYER
3,10001,3509,1,0,0,NaN,2693.0,3540763.0,FORMER_NATIONAL_PLAYER
4,10001,21103,11,0,0,NaN,NaN,NaN,FORMER_NATIONAL_PLAYER

📂 Folder: player_teammates_played_with

📄 File: player_teammates_played_with.csv
Columns: ['player_id', 'teammate_player_id', 'teammate_player_name', 'ppg_played_with', 'joint_goal_participation', 'minutes_played_with']
Missing values:
 player_id                    0
teammate_player_id           0
teammate_player_name         0
ppg_played_with              0
joint_goal_participation    87
minutes_played_with         49
dtype: int64
Data types:
 player_id                     int64
teammate_player_id            int64
teammate_player_name         object
ppg_played_with             float64
joint_goal_participation    float64
minutes_played_with         float64
dtype: object

,player_id,teammate_player_id,teammate_player_name,ppg_played_with,joint_goal_participation,minutes_played_with
0,100001,116163,Leonardo Jara,1.69,2.0,NaN
1,100001,184672,Guido Carrillo,1.74,4.0,NaN
2,100001,222052,Gastón Gil Romero,1.64,1.0,NaN
3,100001,117874,Rafael Pérez,1.65,NaN,NaN
4,100001,533568,Nahuel Tenaglia,1.77,1.0,NaN

📂 Folder: team_children

📄 File: team_children.csv
Columns: ['parent_team_id', 'parent_team_name', 'child_team_id', 'child_team_name', '_last_modified_at']
Missing values:
 parent_team_id       0
parent_team_name     0
child_team_id        0
child_team_name      0
_last_modified_at    0
dtype: int64
Data types:
 parent_team_id        int64
parent_team_name     object
child_team_id         int64
child_team_name      object
_last_modified_at    object
dtype: object

,parent_team_id,parent_team_name,child_team_id,child_team_name,_last_modified_at
0,10370,Racing Club Harelbeke,10370,Racing Club Harelbeke,2025-09-13 13:11:27
1,10370,Racing Club Harelbeke,81362,Racing Harelbeke U21,2025-09-13 13:11:27
2,10370,Racing Club Harelbeke,78589,Racing Harelbeke Jugend,2025-09-13 13:11:27
3,1060,Colchester United,1060,Colchester United,2025-09-13 10:18:58
4,1060,Colchester United,45633,Colchester United U21,2025-09-13 10:18:58

📂 Folder: player_profiles

📄 File: player_profiles.csv
Columns: ['player_id', 'player_slug', 'player_name', 'player_image_url', 'name_in_home_country', 'date_of_birth', 'place_of_birth', 'country_of_birth', 'height', 'citizenship', 'is_eu', 'position', 'main_position', 'foot', 'current_club_id', 'current_club_name', 'joined', 'contract_expires', 'outfitter', 'social_media_url', 'player_agent_id', 'player_agent_name', 'contract_option', 'date_of_last_contract_extension', 'on_loan_from_club_id', 'on_loan_from_club_name', 'contract_there_expires', 'second_club_url', 'second_club_name', 'third_club_url', 'third_club_name', 'fourth_club_url', 'fourth_club_name', 'date_of_death']
Missing values:
 player_id                            0
player_slug                          0
player_name                          3
player_image_url                     0
name_in_home_country                48
date_of_birth                        1
place_of_birth                      29
country_of_birth                    29
height                               0
citizenship                          0
is_eu                                0
position                             0
main_position                        0
foot                                33
current_club_id                      0
current_club_name                    0
joined                               3
contract_expires                    62
outfitter                           99
social_media_url                    82
player_agent_id                     57
player_agent_name                   50
contract_option                     95
date_of_last_contract_extension     97
on_loan_from_club_id                99
on_loan_from_club_name              99
contract_there_expires              99
second_club_url                    100
second_club_name                   100
third_club_url                     100
third_club_name                    100
fourth_club_url                    100
fourth_club_name                   100
date_of_death                      100
dtype: int64
Data types:
 player_id                            int64
player_slug                         object
player_name                         object
player_image_url                    object
name_in_home_country                object
date_of_birth                       object
place_of_birth                      object
country_of_birth                    object
height                             float64
citizenship                         object
is_eu                                 bool
position                            object
main_position                       object
foot                                object
current_club_id                      int64
current_club_name                   object
joined                              object
contract_expires                    object
outfitter                           object
social_media_url                    object
player_agent_id                    float64
player_agent_name                   object
contract_option                     object
date_of_last_contract_extension     object
on_loan_from_club_id               float64
on_loan_from_club_name              object
contract_there_expires              object
second_club_url                    float64
second_club_name                   float64
third_club_url                     float64
third_club_name                    float64
fourth_club_url                    float64
fourth_club_name                   float64
date_of_death                      float64
dtype: object

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,on_loan_from_club_id,on_loan_from_club_name,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death
0,1,silvio-adzic,Silvio Adzic (1),https://img.a.transfermarkt.technology/portrai...,NaN,1980-09-23,Grünstadt,Germany,0.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,john-thompson,John Thompson (10001),https://img.a.transfermarkt.technology/portrai...,John Paul Thompson,1981-10-12,Dublin,Ireland,183.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import os

MATCH_PATH = "/content/data/data/open-data/data/matches"

# List competition folders
competitions = os.listdir(MATCH_PATH)

print("Competitions available:")
print(competitions[:10])

Competitions available:
['11', '223', '2', '1267', '87', '16', '12', '49', '7', '1238']

In [ ]:
import json
import pandas as pd

# Pick one competition
comp_id = competitions[0]

comp_path = os.path.join(MATCH_PATH, comp_id)

# List season files
files = os.listdir(comp_path)
print("Season files:", files[:5])

# Load one file
file_path = os.path.join(comp_path, files[0])

with open(file_path, "r") as f:
    matches = json.load(f)

matches_df = pd.DataFrame(matches)

matches_df.head()

Season files: ['24.json', '26.json', '4.json', '278.json', '22.json']

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,266015,2012-12-22,18:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 24, 'season_name': '2012/2013'}","{'home_team_id': 901, 'home_team_name': 'Real ...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,3,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",17,"{'id': 1, 'name': 'Regular Season'}","{'id': 622, 'name': 'Estadio Municipal José Zo...","{'id': 1008, 'name': 'Carlos Clos Gómez', 'cou..."
1,70270,2012-09-22,22:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 24, 'season_name': '2012/2013'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 1049, 'away_team_name': 'Gran...",2,0,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...",NaN
2,70281,2013-05-05,21:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 24, 'season_name': '2012/2013'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 218, 'away_team_name': 'Real ...",4,2,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",34,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 1008, 'name': 'Carlos Clos Gómez', 'cou..."
3,70308,2012-11-03,18:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 24, 'season_name': '2012/2013'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 209, 'away_team_name': 'Celta...",3,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",10,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 222, 'name': 'David Fernández Borbalan'..."
4,70282,2013-02-03,19:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 24, 'season_name': '2012/2013'}","{'home_team_id': 207, 'home_team_name': 'Valen...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",22,"{'id': 1, 'name': 'Regular Season'}","{'id': 344, 'name': 'Estadio de Mestalla', 'co...","{'id': 211, 'name': 'José Luis González Gonzál..."

Data Exploration Summary
1. Overview

In this project, three datasets were explored:

Transfermarkt-Datasets → contains match and player appearance data
Transfermarkt → contains player injury history
Open-data (StatsBomb) → contains detailed match data in JSON format

Each dataset has a different structure and purpose. The goal of the exploration was to identify which data can be used to build a dataset for predicting injuries.

2. Useful Data for the Project
Transfermarkt-Datasets (Main Feature Source)

The most important table is:

appearances
One row per player per match
Includes:
player_id
date
minutes_played

This table is used to measure player workload

We can use it to create features such as:

total minutes played
number of matches played
recent workload over time
Supporting table: games
Provides match context (date, competition)

Useful for:

checking dates
understanding match schedule
Open-data (matches)
Contains match data in JSON format
Required preprocessing (nested structure)

However:

it uses different IDs than Transfermarkt
cannot be merged reliably

Therefore, it is not used in the model, only for exploration

3. Injury Data (Target Variable)
player_injuries
One row per injury period
Includes:
player_id
from_date
end_date
days_missed
injury_reason

This data is used to define whether a player gets injured

Important point:

Injuries are stored as time intervals, not single events
So we convert them into:
an injury event (start date)
a binary label (injury in next 14 days)
4. Feature Engineering

Using the appearances table, we create:

Workload features
minutes_7d, minutes_14d, minutes_28d
matches_7d, matches_14d, matches_28d
⏱ Recovery feature
days_since_last_match
Match role
is_starter / is_sub (based on minutes)

All features are computed using only past data (no future leakage)

5. Final Dataset Structure

We build a player-day dataset, where:

each row = one player on one day
includes:
workload features
recovery features
injury label

Example:

player_id	date	minutes_14d	matches_7d	days_since_last_match	injury_next_14d
6. Joinability Check

The datasets can be combined because:

player_id is consistent across datasets
match dates and injury dates overlap

This allows us to link:

past workload → future injury
7. Limitations
No training data (GPS, fitness, wellness)
Injury reasons are not standardized
Injuries are rare (class imbalance)
8. Conclusion

The data exploration shows that:

Transfermarkt-Datasets can be used to measure player workload
Transfermarkt provides injury labels
Both datasets can be combined to build a player-level injury prediction dataset

This dataset will be used to train a model that predicts injuries in the next 14 days based on match exposure.

In [ ]:
import pandas as pd
import numpy as np

# Load data
appearances = pd.read_csv("/content/data/data/transfermarkt-datasets/appearances.csv.gz")
injuries = pd.read_csv("/content/data/data/transfermarkt/player_injuries/player_injuries.csv")

# Convert dates
appearances["date"] = pd.to_datetime(appearances["date"])
injuries["from_date"] = pd.to_datetime(injuries["from_date"])
injuries["end_date"] = pd.to_datetime(injuries["end_date"])

# Build Base Exposure Table (match-level)

In [ ]:
df = appearances.copy()

# Match indicator
df["match_flag"] = (df["minutes_played"] > 0).astype(int)

# Starter / sub (simple rule)
df["is_starter"] = (df["minutes_played"] >= 60).astype(int)
df["is_sub"] = ((df["minutes_played"] > 0) & (df["minutes_played"] < 60)).astype(int)

# Sort for time-based features
df = df.sort_values(["player_id", "date"])

# Prevent Leakage (SHIFT EVERYTHING)

In [ ]:
df["minutes_lag"] = df.groupby("player_id")["minutes_played"].shift(1)
df["match_lag"] = df.groupby("player_id")["match_flag"].shift(1)
df["starter_lag"] = df.groupby("player_id")["is_starter"].shift(1)

# Rolling Features (Core Signal)

In [ ]:
df = df.sort_values(["player_id", "date"])

df = df.set_index("date")

# Rolling temporel
df["minutes_7d"] = (
    df.groupby("player_id")["minutes_lag"]
    .rolling("7D")
    .sum()
    .reset_index(0, drop=True)
)

df["minutes_14d"] = (
    df.groupby("player_id")["minutes_lag"]
    .rolling("14D")
    .sum()
    .reset_index(0, drop=True)
)

df["minutes_28d"] = (
    df.groupby("player_id")["minutes_lag"]
    .rolling("28D")
    .sum()
    .reset_index(0, drop=True)
)

In [ ]:
df = df.sort_values(["player_id", df.index.name])

In [ ]:
df["match_flag"] = (df["minutes_played"] > 0).astype(int)

df["match_lag"] = df.groupby("player_id")["match_flag"].shift(1)

In [ ]:
# rolling 7 jours
df["matches_7d"] = (
    df.groupby("player_id")["match_lag"]
    .rolling("7D")
    .sum()
    .reset_index(level=0, drop=True)
)

# rolling 14 jours
df["matches_14d"] = (
    df.groupby("player_id")["match_lag"]
    .rolling("14D")
    .sum()
    .reset_index(level=0, drop=True)
)

# rolling 28 jours
df["matches_28d"] = (
    df.groupby("player_id")["match_lag"]
    .rolling("28D")
    .sum()
    .reset_index(level=0, drop=True)
)

In [ ]:
df[["matches_7d", "matches_14d", "matches_28d"]] = \
    df[["matches_7d", "matches_14d", "matches_28d"]].fillna(0)

In [ ]:
df.columns

Index(['appearance_id', 'game_id', 'player_id', 'player_club_id',
       'player_current_club_id', 'player_name', 'competition_id',
       'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played',
       'match_flag', 'is_starter', 'is_sub', 'minutes_lag', 'match_lag',
       'starter_lag', 'minutes_7d', 'minutes_14d', 'minutes_28d', 'matches_7d',
       'matches_14d', 'matches_28d'],
      dtype='object')

# Days Since Last Match

In [ ]:
df["prev_match_date"] = df.groupby("player_id").apply(
    lambda x: x.index.to_series().shift(1)
).reset_index(level=0, drop=True)

df["days_since_last_match"] = (
    df.index - df["prev_match_date"]
).dt.days

/tmp/ipykernel_366/1260654366.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df["prev_match_date"] = df.groupby("player_id").apply(

# Last Match Context

In [ ]:
df["minutes_last_match"] = df.groupby("player_id")["minutes_played"].shift(1)
df["started_last_match"] = df.groupby("player_id")["is_starter"].shift(1)

df["sub_last_match"] = (
    (df["minutes_last_match"] > 0) &
    (df["started_last_match"] == 0)
).astype(int)

# Build Injury Label (14-day horizon)

In [ ]:
# Fill missing end_date
injuries["end_date"] = injuries["end_date"].fillna(
    injuries["from_date"] + pd.to_timedelta(injuries["days_missed"], unit="D")
)

# Filter relevant injuries (optional but recommended)
keywords = ["hamstring", "thigh", "groin", "calf", "muscle"]

injuries = injuries[
    injuries["injury_reason"].str.lower().str.contains("|".join(keywords))
]

# Create label

In [ ]:
import numpy as np
import pandas as pd

# sécurité : s'assurer que tout est bien en datetime
df.index = pd.to_datetime(df.index)
injuries["from_date"] = pd.to_datetime(injuries["from_date"])

# initialiser le label
df["injury_next_14d"] = 0

# boucle par joueur (efficace + memory safe)
for player_id, group in injuries.groupby("player_id"):

    # dates des blessures du joueur
    injury_dates = group["from_date"].to_numpy(dtype="datetime64[ns]")

    # masque du joueur
    mask_player = df["player_id"] == player_id

    # dates des matchs du joueur (depuis l'index)
    player_dates = df.loc[mask_player].index.to_numpy(dtype="datetime64[ns]")

    # tableau label local (plus rapide que df.loc à chaque fois)
    labels = np.zeros(len(player_dates), dtype=np.int8)

    for injury_date in injury_dates:

        mask = (
            (player_dates < injury_date) &
            (player_dates >= injury_date - np.timedelta64(14, 'D'))
        )

        labels |= mask.astype(np.int8)

    # assigner en une seule fois (très important pour perf)
    df.loc[mask_player, "injury_next_14d"] = labels

In [ ]:
df = df.sort_values(["player_id", df.index.name])

# Joinability Check (VERY IMPORTANT)

In [ ]:
# Player overlap
overlap = set(df["player_id"]) & set(injuries["player_id"])

print("Players in exposure:", df["player_id"].nunique())
print("Players in injuries:", injuries["player_id"].nunique())
print("Overlap:", len(overlap))


# Date ranges (use index instead of column)
print("\nExposure range:", df.index.min(), "→", df.index.max())
print("Injury range:", injuries["from_date"].min(), "→", injuries["from_date"].max())


# Injury rate
print("\nInjury rate:", df["injury_next_14d"].mean())

Players in exposure: 26261
Players in injuries: 14113
Overlap: 8440

Exposure range: 2012-07-03 00:00:00 → 2025-07-13 00:00:00
Injury range: 1974-09-02 00:00:00 → 2025-09-12 00:00:00

Injury rate: 0.011389096125262762

In [ ]:
df = df.sort_values(["player_id", df.index.name])

In [ ]:

df = df.reset_index()

In [ ]:
final_df = df[[
    "player_id",
    "minutes_7d",
    "minutes_14d",
    "minutes_28d",
    "matches_7d",
    "matches_14d",
    "matches_28d",
    "days_since_last_match",
    "minutes_last_match",
    "started_last_match",
    "sub_last_match",
    "injury_next_14d"
]].copy()

final_df.head()

,player_id,minutes_7d,minutes_14d,minutes_28d,matches_7d,matches_14d,matches_28d,days_since_last_match,minutes_last_match,started_last_match,sub_last_match,injury_next_14d
0,10,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,0
1,10,83.0,83.0,83.0,1.0,1.0,1.0,3.0,83.0,1.0,0,0
2,10,90.0,173.0,173.0,1.0,2.0,2.0,7.0,90.0,1.0,0,0
3,10,89.0,89.0,262.0,1.0,1.0,3.0,14.0,89.0,1.0,0,0
4,10,179.0,179.0,352.0,2.0,2.0,4.0,4.0,90.0,1.0,0,0

# Sanity Checks

# Check no leakage

In [ ]:
final_df[["minutes_last_match", "minutes_7d"]].head(10)

   minutes_last_match  minutes_7d
0                 NaN         NaN
1                83.0        83.0
2                90.0        90.0
3                89.0        89.0
4                90.0       179.0
5                90.0       180.0
6                14.0       194.0
7                90.0       104.0
8                90.0        90.0
9                72.0        72.0

# Check distributions

In [ ]:
final_df.describe()

,player_id,minutes_7d,minutes_14d,minutes_28d,matches_7d,matches_14d,matches_28d,days_since_last_match,minutes_last_match,started_last_match,sub_last_match,injury_next_14d
count,1.734466e+06,1.708205e+06,1.708205e+06,1.708205e+06,1.734466e+06,1.734466e+06,1.734466e+06,1.708205e+06,1.708205e+06,1.708205e+06,1.734466e+06,1.734466e+06
mean,2.144345e+05,9.952534e+01,1.542396e+02,2.511047e+02,1.407156e+00,2.164194e+00,3.499735e+00,1.845192e+01,6.919714e+01,7.243048e-01,2.715210e-01,1.138910e-02
std,1.989757e+05,5.573638e+01,8.784748e+01,1.425582e+02,5.580503e-01,9.328491e-01,1.547390e+00,7.330933e+01,2.989574e+01,4.468641e-01,4.447443e-01,1.061103e-01
min,1.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.894500e+04,6.900000e+01,9.000000e+01,1.340000e+02,1.000000e+00,2.000000e+00,2.000000e+00,5.000000e+00,4.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.561370e+05,9.000000e+01,1.640000e+02,2.600000e+02,1.000000e+00,2.000000e+00,4.000000e+00,7.000000e+00,9.000000e+01,1.000000e+00,0.000000e+00,0.000000e+00
75%,3.153370e+05,1.490000e+02,2.030000e+02,3.600000e+02,2.000000e+00,3.000000e+00,4.000000e+00,1.300000e+01,9.000000e+01,1.000000e+00,1.000000e+00,0.000000e+00
max,1.411351e+06,3.300000e+02,5.100000e+02,9.000000e+02,3.000000e+00,5.000000e+00,9.000000e+00,3.934000e+03,1.480000e+02,1.000000e+00,1.000000e+00,1.000000e+00

In [ ]:
print(df.columns)

Index(['appearance_id', 'game_id', 'player_id', 'player_club_id',
       'player_current_club_id', 'player_name', 'competition_id',
       'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played',
       'match_flag', 'is_starter', 'is_sub', 'minutes_lag', 'match_lag',
       'starter_lag', 'minutes_7d', 'minutes_14d', 'minutes_28d'],
      dtype='object')

In [ ]:
!git clone https://github.com/ozifrs/football-injury-risk-prediction.git

Cloning into 'football-injury-risk-prediction'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 25 (delta 11), reused 20 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 776.61 KiB | 3.04 MiB/s, done.
Resolving deltas: 100% (11/11), done.

In [ ]:
git init

Collecting numpy==2.4.2 (from -r requirements.txt (line 2))
  Downloading numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas==3.0.1 (from -r requirements.txt (line 3))
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.5 MB/s eta 0:00:00
Collecting matplotlib==3.10.8 (from -r requirements.txt (line 4))
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (2.32.4)
Collecting mplsoccer (from -r requirements.txt (line 11))
  Downloading mplsoccer-1.6.1-py3-none-any.whl.metadata (4.8 kB)
Collecting skillcorner==3.0.0 (from -r requirements.txt (line 12))
  Downloading skillcorner-3.0.0-py3-none-any.whl.metadata (4.2 kB)
Collecting skillcornerviz==1.1.2 (from -r requirements.txt (line 13))
  Downloading skillcornerviz-1.1.2-py3-none-any.whl.metadata (13 kB)
Collecting kloppy (from -r requirements.txt (line 14))
  Downloading kloppy-3.18.0-py3-none-any.whl.metadata (11 kB)
Collecting ipykernel==7.2.0 (from -r requirements.txt (line 17))
  Downloading ipykernel-7.2.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.1->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 4)) (3.3.2)
Collecting fitrequest~=1.5.2 (from skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading fitrequest-1.5.3-py3-none-any.whl.metadata (7.0 kB)
Collecting makefun>=1.15.6 (from skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading makefun-1.16.0-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: orjson>=3.9.10 in /usr/local/lib/python3.12/dist-packages (from skillcorner==3.0.0->-r requirements.txt (line 12)) (3.11.7)
Collecting progress>=1.6 (from skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading progress-1.6.1-py3-none-any.whl.metadata (4.3 kB)
Collecting adjustText>=0.7.3 (from skillcornerviz==1.1.2->-r requirements.txt (line 13))
  Downloading adjustText-1.3.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: setuptools>=65.0.0 in /usr/local/lib/python3.12/dist-packages (from skillcornerviz==1.1.2->-r requirements.txt (line 13)) (75.2.0)
Collecting comm>=0.1.1 (from ipykernel==7.2.0->-r requirements.txt (line 17))
  Downloading comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (7.34.0)
Collecting jupyter-client>=8.8.0 (from ipykernel==7.2.0->-r requirements.txt (line 17))
  Downloading jupyter_client-8.8.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (5.9.5)
Requirement already satisfied: pyzmq>=25 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (26.2.1)
Requirement already satisfied: tornado>=6.4.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel==7.2.0->-r requirements.txt (line 17)) (5.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 8)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 8)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 8)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 8)) (2026.2.25)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mplsoccer->-r requirements.txt (line 11)) (1.16.3)
Requirement already satisfied: lxml>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from kloppy->-r requirements.txt (line 14)) (6.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from kloppy->-r requirements.txt (line 14)) (2025.2)
Collecting sortedcontainers>=2 (from kloppy->-r requirements.txt (line 14))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: fsspec>=2024.12.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (2025.3.0)
Requirement already satisfied: aiofiles>=24.1.0 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (24.1.0)
Collecting boto3>=1.34.96 (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading boto3-1.42.73-py3-none-any.whl.metadata (6.7 kB)
Collecting clustershell>=1.9.2 (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading ClusterShell-1.9.3.tar.gz (417 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.1/417.1 kB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: defusedxml>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.7.1)
Requirement already satisfied: httpx>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.28.1)
Requirement already satisfied: jinja2>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (3.1.6)
Collecting jsonpath-ng>=1.7.0 (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading jsonpath_ng-1.8.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pydantic-settings>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (2.13.1)
Requirement already satisfied: pydantic>=2.5.2 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (2.12.3)
Requirement already satisfied: rich>=13.9.4 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (13.9.4)
Collecting strenum>=0.4.15 (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: tenacity>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (9.1.4)
Requirement already satisfied: typer>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.24.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (3.13.3)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17))
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (4.9.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (4.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==3.0.1->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2024.12.0->kloppy->-r requirements.txt (line 14)) (1.23.0)
Collecting botocore<1.43.0,>=1.42.73 (from boto3>=1.34.96->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading botocore-1.42.73-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.34.96->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.34.96->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12))
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from clustershell>=1.9.2->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (6.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.28.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (0.8.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.1.4->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (3.0.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel==7.2.0->-r requirements.txt (line 17)) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.2->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.2->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.2->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.2->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.6.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.9.4->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (4.0.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.15.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.15.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.15.1->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.0.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.9.4->fitrequest~=1.5.2->skillcorner==3.0.0->-r requirements.txt (line 12)) (0.1.2)
Downloading numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 70.7 MB/s eta 0:00:00
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 96.3 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 89.6 MB/s eta 0:00:00
Downloading skillcorner-3.0.0-py3-none-any.whl (7.8 kB)
Downloading skillcornerviz-1.1.2-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 4.5 MB/s eta 0:00:00
Downloading ipykernel-7.2.0-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 kB 10.1 MB/s eta 0:00:00
Downloading mplsoccer-1.6.1-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 8.3 MB/s eta 0:00:00
Downloading kloppy-3.18.0-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.7/294.7 kB 23.6 MB/s eta 0:00:00
Downloading adjustText-1.3.0-py3-none-any.whl (13 kB)
Downloading comm-0.2.3-py3-none-any.whl (7.3 kB)
Downloading fitrequest-1.5.3-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 2.9 MB/s eta 0:00:00
Downloading jupyter_client-8.8.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 9.2 MB/s eta 0:00:00
Downloading makefun-1.16.0-py2.py3-none-any.whl (22 kB)
Downloading progress-1.6.1-py3-none-any.whl (9.8 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading boto3-1.42.73-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 12.0 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 71.5 MB/s eta 0:00:00
Downloading jsonpath_ng-1.8.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 6.0 MB/s eta 0:00:00
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Downloading botocore-1.42.73-py3-none-any.whl (14.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 49.6 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.5 MB/s eta 0:00:00
Building wheels for collected packages: clustershell
  Building wheel for clustershell (setup.py) ... done
  Created wheel for clustershell: filename=ClusterShell-1.9.3-py3-none-any.whl size=501688 sha256=9c151d044ff1a151d1273f0ff51f538aa44c0a6c8d70855d8ded9dbd39f5f26a
  Stored in directory: /root/.cache/pip/wheels/d8/98/20/ef73d17dc457f96bd79404820b319c22b30b174b23a7256153
Successfully built clustershell
Installing collected packages: strenum, sortedcontainers, makefun, jsonpath-ng, progress, numpy, jmespath, jedi, comm, clustershell, pandas, jupyter-client, botocore, s3transfer, matplotlib, ipykernel, kloppy, boto3, adjustText, skillcornerviz, mplsoccer, fitrequest, skillcorner
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter_client 7.4.9
    Uninstalling jupyter_client-7.4.9:
      Successfully uninstalled jupyter_client-7.4.9
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.0
    Uninstalling matplotlib-3.10.0:

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/02_transfermarkt_exposure_exploration.ipynb" \
/content/football-injury-risk-prediction/notebooks/

In [120]:
!git remote remove origin

In [121]:
!git remote add origin https://github.com/Mandella_2000/football-injury-risk-prediction.git

In [123]:
!git add .

In [128]:
!git config --global user.email "fmamendella@email.com"
!git config --global user.name "Mandella2000"

In [129]:
!git commit -m "Add player exposure dataset + injury label pipeline"

On branch main
nothing to commit, working tree clean

In [130]:
!git push --set-upstream origin main

fatal: could not read Username for 'https://github.com': No such device or address